openapi: 3.0.0
info:
  title: 'ONDC Registry '
  description: ONDC Participant Management API
  version: 2.0.5
servers:
- url: https://virtserver.swaggerhub.com/ONDC/ONDC-Registry-Onboarding/2.0.5
  description: SwaggerHub API Auto Mocking
tags:
- name: ONDC Network Participant Onboarding
  description: "Registration, amendment, key rotation"
paths:
  /subscribe:
    post:
      tags:
      - ONDC Network Participant Onboarding
      description: subscriber
      operationId: subscribePOST
      requestBody:
        description: Onboard
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/subscribe_body'
            examples:
              ops_no_1:
                value:
                  context:
                    operation:
                      ops_no: 1
                    request_id: 27baa06d-f90a-486c-85e5-cc621b787f04
                    timestamp: 2022-07-08T13:44:54.101Z
                    entity:
                      gst:
                        legal_entity_name: ABC Incorporates
                        business_address: "Trade World, Mansarpur, Coorg, Karnataka\
                          \ 333333"
                        city_code:
                        - std:080
                        gst_no: 07AAACN2082N4Z7
                      pan:
                        name_as_per_pan: ABC Incorporates
                        pan_no: ASDFP7657Q
                        date_of_incorporation: 23/06/1982
                      name_of_authorised_signatory: Anand Sharma
                      address_of_authorised Signatory: "405, Pinnacle House, Kandiwali,\
                        \ Mumbai 400001"
                      email_id: anand.sharma@abc.com
                      mobile_no: 9912332199
                      country: IND
                      subscriber_id: sit.grab.in
                      unique_key_id: 27baa06d-f90a-486c-85e5-cc621b787f04
                      callback_url: /ondc/onboarding
                      key_pair:
                        signing_public_key: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
                        encryption_public_key: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
                        valid_from: 2022-07-08T13:44:54.101Z
                        valid_until: 2022-07-08T13:44:54.101Z
                    network_participant:
                    - subscriber_url: /bapl
                      domain: nic2004:52110
                      type: buyerApp
                      msn: false
                      city_code:
                      - std:080
              ops_no_2:
                value:
                  context:
                    operation:
                      ops_no: 2
                  message:
                    request_id: 27baa06d-f90a-486c-85e5-cc621b787f04
                    timestamp: 2022-07-08T13:44:54.101Z
                    entity:
                      gst:
                        legal_entity_name: ABC Incorporates
                        business_address: "Trade World, Mansarpur, Coorg, Karnataka\
                          \ 333333"
                        city_code:
                        - std:080
                        gst_no: 07AAACN2082N4Z7
                      pan:
                        name_as_per_pan: ABC Incorporates
                        pan_no: ASDFP7657Q
                        date_of_incorporation: 23/06/1982
                      name_of_authorised_signatory: Anand Sharma
                      address_of_authorised Signatory: "405, Pinnacle House, Kandiwali,\
                        \ Mumbai 400001"
                      email_id: anand.sharma@abc.com
                      mobile_no: 9912332199
                      country: IND
                      subscriber_id: sit.grab.in
                      unique_key_id: 27baa06d-f90a-486c-85e5-cc621b787f04
                      callback_url: /ondc/onboarding
                      key_pair:
                        signing_public_key: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
                        encryption_public_key: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
                        valid_from: 2022-07-08T13:44:54.101Z
                        valid_until: 2022-07-08T13:44:54.101Z
                    network_participant:
                    - subscriber_url: /bapl
                      domain: nic2004:52110
                      type: sellerApp
                      msn: false
                      city_code:
                      - std:080
              ops_no_3:
                value:
                  context:
                    operation:
                      ops_no: 3
                  message:
                    request_id: 27baa06d-f90a-486c-85e5-cc621b787f04
                    timestamp: 2022-07-08T13:44:54.101Z
                    entity:
                      gst:
                        legal_entity_name: ABC Incorporates
                        business_address: "Trade World, Mansarpur, Coorg, Karnataka\
                          \ 333333"
                        city_code:
                        - std:080
                        gst_no: 07AAACN2082N4Z7
                      pan:
                        name_as_per_pan: ABC Incorporates
                        pan_no: ASDFP7657Q
                        date_of_incorporation: 23/06/1982
                      name_of_authorised_signatory: Anand Sharma
                      address_of_authorised Signatory: "405, Pinnacle House, Kandiwali,\
                        \ Mumbai 400001"
                      email_id: anand.sharma@abc.com
                      mobile_no: 9912332199
                      country: IND
                      subscriber_id: sit.grab.in
                      unique_key_id: 27baa06d-f90a-486c-85e5-cc621b787f04
                      callback_url: /ondc/onboarding
                      key_pair:
                        signing_public_key: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
                        encryption_public_key: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
                        valid_from: 2022-07-08T13:44:54.101Z
                        valid_until: 2022-07-08T13:44:54.101Z
                    network_participant:
                      subscriber_url: /bapl
                      domain: nic2004:52110
                      type: sellerApp
                      msn: true
                      city_code:
                      - std:080
                      seller_on_record:
                      - unique_key_id: 27baa06d-f90a-486c-85e5-cc621b787f04
                        key_pair:
                          signing_public_key: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
                          encryption_public_key: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
                          valid_from: 2022-07-08T13:44:54.101Z
                          valid_until: 2022-07-08T13:44:54.101Z
                        city_code:
                        - std:080
              ops_no_4:
                value:
                  context:
                    operation:
                      ops_no: 4
                  message:
                    request_id: 27baa06d-f90a-486c-85e5-cc621b787f04
                    timestamp: 2022-07-08T13:44:54.101Z
                    entity:
                      gst:
                        legal_entity_name: ABC Incorporates
                        business_address: "Trade World, Mansarpur, Coorg, Karnataka\
                          \ 333333"
                        city_code:
                        - std:080
                        gst_no: 07AAACN2082N4Z7
                      pan:
                        name_as_per_pan: ABC Incorporates
                        pan_no: ASDFP7657Q
                        date_of_incorporation: 23/06/1982
                      name_of_authorised_signatory: Anand Sharma
                      address_of_authorised Signatory: "405, Pinnacle House, Kandiwali,\
                        \ Mumbai 400001"
                      email_id: anand.sharma@abc.com
                      mobile_no: 9912332199
                      country: IND
                      subscriber_id: sit.grab.in
                      unique_key_id: 27baa06d-f90a-486c-85e5-cc621b787f04
                      callback_url: /ondc/onboarding
                      key_pair:
                        signing_public_key: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
                        encryption_public_key: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
                        valid_from: 2022-07-08T13:44:54.101Z
                        valid_until: 2022-07-08T13:44:54.101Z
                    network_participant:
                    - subscriber_url: /buyerAppl
                      domain: nic2004:52110
                      type: buyerApp
                      msn: false
                      city_code:
                      - std:080
                    - subscriber_url: /sellerAppl
                      domain: nic2004:52110
                      type: sellerApp
                      msn: false
                      city_code:
                      - std:080
              ops_no_5:
                value:
                  context:
                    operation:
                      ops_no: 5
                  message:
                    request_id: 27baa06d-f90a-486c-85e5-cc621b787f04
                    timestamp: 2022-07-08T13:44:54.101Z
                    entity:
                      gst:
                        legal_entity_name: ABC Incorporates
                        business_address: "Trade World, Mansarpur, Coorg, Karnataka\
                          \ 333333"
                        city_code:
                        - std:080
                        gst_no: 07AAACN2082N4Z7
                      pan:
                        name_as_per_pan: ABC Incorporates
                        pan_no: ASDFP7657Q
                        date_of_incorporation: 23/06/1982
                      name_of_authorised_signatory: Anand Sharma
                      address_of_authorised Signatory: "405, Pinnacle House, Kandiwali,\
                        \ Mumbai 400001"
                      email_id: anand.sharma@abc.com
                      mobile_no: 9912332199
                      country: IND
                      subscriber_id: sit.grab.in
                      unique_key_id: 27baa06d-f90a-486c-85e5-cc621b787f04
                      callback_url: /ondc/onboarding
                      key_pair:
                        signing_public_key: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
                        encryption_public_key: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
                        valid_from: 2022-07-08T13:44:54.101Z
                        valid_until: 2022-07-08T13:44:54.101Z
                    network_participant:
                    - subscriber_url: /buyerApp1
                      domain: nic2004:52110
                      type: buyerApp
                      msn: false
                      city_code:
                      - std:080
                    - subscriber_url: /sellerApp1
                      domain: nic2004:52110
                      type: sellerApp
                      msn: true
                      city_code:
                      - std:080
                      seller_on_record:
                      - unique_key_id: 27baa06d-f90a-486c-85e5-cc621b787f04
                        key_pair:
                          signing_public_key: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
                          encryption_public_key: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
                          valid_from: 2022-07-08T13:44:54.101Z
                          valid_until: 2022-07-08T13:44:54.101Z
                        city_code:
                        - std:080
      responses:
        "200":
          description: Acknowledgement of message received
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
      x-swagger-router-controller: ONDCNetworkParticipantOnboarding
  /subscriber_url/on_subscribe:
    post:
      tags:
      - ONDC Network Participant Onboarding
      description: to be hosted by subscriber
      operationId: subscriber_urlOn_subscribePOST
      requestBody:
        description: Onboard
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/subscriber_url_on_subscribe_body'
      responses:
        "200":
          description: Successful subscription
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
      x-swagger-router-controller: ONDCNetworkParticipantOnboarding
  /lookup:
    post:
      tags:
      - ONDC Network Participant Onboarding
      description: subscriber
      operationId: lookupPOST
      requestBody:
        description: Onboard
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/lookup_body'
      responses:
        "200":
          description: Acknowledgement of message received
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_2'
                x-content-type: application/json
      x-swagger-router-controller: ONDCNetworkParticipantOnboarding
  /vlookup:
    post:
      tags:
      - Key rotation of network participant - buyerApp or sellerApp
      summary: Get public keys of network participants
      description: The network participant will trigger the lookup call to the registry
        to fetch its public keys.
      operationId: vlookupPOST
      requestBody:
        description: vlookup
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/vlookup_body'
      responses:
        "200":
          description: VLookup received
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_3'
                x-content-type: application/json
        "401":
          description: "Unauthorized Access: invalid signature."
        "411":
          description: timestamp is invalid.
        "412":
          description: sender subscriber id is invalid.
        "416":
          description: Atleast two search parameters is required.
        "500":
          description: Server Side Error. Call Helpdesk for details.
      x-swagger-router-controller: KeyRotationOfNetworkParticipantBuyerAppOrSellerApp
components:
  schemas:
    Ack:
      required:
      - status
      type: object
      properties:
        status:
          type: string
          description: "Describe the status of the ACK response. If schema validation\
            \ passes, status is ACK else it is NACK"
          enum:
          - ACK
          - NACK
      description: Describes the ACK response
      example:
        status: ACK
    Error:
      required:
      - code
      - type
      type: object
      properties:
        type:
          type: string
          enum:
          - CONTEXT-ERROR
          - CORE-ERROR
          - DOMAIN-ERROR
          - POLICY-ERROR
          - JSON-SCHEMA-ERROR
        code:
          type: string
          description: "ONDC specific error code. For full list of error codes, refer\
            \ to docs/drafts/Error Codes.md of this repo"
        path:
          type: string
          description: Path to json schema generating the error. Used only during
            json schema validation errors
        message:
          type: string
          description: Human readable message describing the error
      description: Describes an error object
      example:
        path: path
        code: code
        type: CONTEXT-ERROR
        message: message
    Context:
      type: object
      properties:
        ops_no:
          type: integer
          description: 1 - Buyer New entity registration <br> 2 - Non-MSN Seller New
            entity registration <br> 3 - MSN Seller New entity registration <br> 4
            - Buyer and Non-MSN Seller new registration  <br> 5 - Buyer and MSN Seller
            new registration <br> 6 - Buyer/Non-MSN/MSN SellerApp key rotation <br>
            7 - MSN Seller changing keys for Seller on Record  <br> 8 - Buyer adding
            New network participant for Non-MSN Seller <br> 9 - Buyer adding New network
            participant for MSN Seller <br> 10 - MSN Seller adding new seller on record
            <br> 11 - BuyerApp/SellerApp amending city <br> 12 - MSN Seller amending
            Seller on record city  <br>
          format: int32
          example: 1
          enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
    Entity:
      type: object
      properties:
        gst:
          $ref: '#/components/schemas/Entity_gst'
        pan:
          $ref: '#/components/schemas/Entity_pan'
        name_of_authorised_signatory:
          type: string
          example: Anand Sharma
        address_of_authorised Signatory:
          type: string
          example: "405, Pinnacle House, Kandiwali, Mumbai 400001"
        email_id:
          type: string
          example: anand.sharma@abc.com
        mobile_no:
          type: string
          example: "9912332199"
        country:
          type: string
          description: Country code as per ISO 3166-1 and ISO 3166-2 format
          example: IND
        subscriber_id:
          type: string
          example: sit.grab.in
        callback_url:
          type: string
          description: "it should be relative to subscriber_id mentioned domain. In\
            \ below example with subscriber _id as abc.com, regsitry will call https://abc.com/ondc/onboarding/on_subscribe"
          example: /ondc/onboarding
        key_pair:
          $ref: '#/components/schemas/KeyPair'
    NetworkParticipant:
      type: object
      properties:
        subscriber_url:
          type: string
          example: /bapl
        domain:
          type: string
          description: Industry domain of the subscriber
          example: nic2004:52110
        type:
          type: string
          enum:
          - buyerApp
          - sellerApp
          - gateway
        msn:
          type: string
        city_code:
          type: array
          items:
            $ref: '#/components/schemas/City'
        seller_on_record:
          type: array
          items:
            $ref: '#/components/schemas/SellerOnRecord'
    SellerOnRecord:
      type: object
      properties:
        unique_key_id:
          type: string
        key_pair:
          $ref: '#/components/schemas/KeyPair'
        city_code:
          type: array
          items:
            $ref: '#/components/schemas/City'
    City:
      type: string
      description: "Codification of city code will be using the std code of the city\
        \ e.g. for Bengaluru, city code is 'std:080'"
      example: std:080
    KeyPair:
      type: object
      properties:
        signing_public_key:
          type: string
          format: byte
          example: !!binary |-
            UVNheDJLVDRVaVRVV1Vxb1ZVYUVjV2hCY0dUVE51K1NmOEVNRFJZMUdhRT0=
        encryption_public_key:
          type: string
          format: byte
          example: !!binary |-
            Tzc0dWtNeW1rNEtablZzM3NaaFUyVTdSWHBhWi9xaU9VTWs1Tld0NnJiST0=
        valid_from:
          type: string
          description: use IST time zone
          format: date-time
          example: 2022-07-07T02:52:29.001Z
        valid_until:
          type: string
          description: use IST time zone
          format: date-time
          example: 2022-07-07T02:52:29.001Z
    subscribe_context:
      type: object
      properties:
        operation:
          $ref: '#/components/schemas/Context'
    subscribe_message:
      required:
      - entity
      - network_participant
      - timestamp
      type: object
      properties:
        request_id:
          type: string
          description: A unique request id generated by network participant to track
            each request.
        timestamp:
          type: string
          description: Time of request generation in RFC3339 format
          format: date-time
          example: 2022-07-07T02:52:29.001Z
        entity:
          $ref: '#/components/schemas/Entity'
        network_participant:
          type: array
          items:
            $ref: '#/components/schemas/NetworkParticipant'
    subscribe_body:
      required:
      - context
      - message
      type: object
      properties:
        context:
          $ref: '#/components/schemas/subscribe_context'
        message:
          $ref: '#/components/schemas/subscribe_message'
    inline_response_200:
      required:
      - message
      type: object
      properties:
        message:
          $ref: '#/components/schemas/inline_response_200_message'
        error:
          $ref: '#/components/schemas/Error'
      example:
        message:
          ack:
            status: ACK
        error:
          path: path
          code: code
          type: CONTEXT-ERROR
          message: message
    subscriber_url_on_subscribe_body:
      type: object
      properties:
        subscriber_id:
          type: string
          description: A unique ID describing a subscriber on a network.
          example: abc.com
        challenge:
          type: string
          description: String encrypted using the subscriber’s old encryption public
            key
          example: encrypted_challenge_string
    inline_response_200_1:
      type: object
      properties:
        answer:
          type: string
          description: Decrypted value
          example: decrypted_challange_string
      example:
        answer: decrypted_challange_string
    lookup_body:
      required:
      - city
      - country
      - domain
      - subscriber_id
      - type
      type: object
      properties:
        subscriber_id:
          type: string
          description: A unique ID describing a subscriber on a network.
        country:
          type: string
          description: Country code as per ISO 3166-1 and ISO 3166-2 format
        ukId:
          type: string
          description: A unique ID describing a subscriber on a network.
        city:
          type: string
          description: City code
          format: string
          example: std:080
        domain:
          type: string
          description: Industry domain of the subscriber.
          format: string
          example: nic2004:52110
        type:
          type: string
          description: BAP or BPP
          format: string
          example: BAP or BPP
    inline_response_200_2:
      type: object
      properties:
        subscriber_id:
          type: string
          description: A unique ID describing a subscriber on a network.
          format: string
          example: https://sit.grab.in/ondc
        ukId:
          type: string
          description: UUID.
          format: string
          example: 22a8a67a-76d9-459b-867c-085dda2939ec
        br_id:
          type: string
          description: UUID.
          format: string
          example: 22a8a67a-76d9-459b-867c-085dda2939ec
        country:
          type: string
          description: Country code
          format: string
          example: IND
        city:
          type: string
          description: City code
          format: string
          example: std:080
        domain:
          type: string
          description: Industry domain of the subscriber.
          format: string
          example: nic2004:52110
        signing_public_key:
          type: string
          description: Signing Public Key
          example: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
        encr_public_key:
          type: string
          description: Encryption Public Key
          example: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
        valid_from:
          type: string
          description: Keys valid from
          format: string ($date-time)
          example: 2022-04-05T05:56:52.470618Z3
        valid_until:
          type: string
          description: Keys valid until
          format: string ($date-time)
          example: 2026-04-05T05:56:52.470618Z7
        created:
          type: string
          description: Created timestamp
          format: string ($date-time)
          example: 2026-04-05T05:56:52.470618Z7
        updated:
          type: string
          description: Updated timestamp
          format: string ($date-time)
          example: 2026-04-05T05:56:52.470618Z7
      example:
        br_id: 22a8a67a-76d9-459b-867c-085dda2939ec
        country: IND
        signing_public_key: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
        subscriber_id: https://sit.grab.in/ondc
        valid_until: 2026-04-05T05:56:52.470618Z7
        city: std:080
        created: 2026-04-05T05:56:52.470618Z7
        ukId: 22a8a67a-76d9-459b-867c-085dda2939ec
        domain: nic2004:52110
        valid_from: 2022-04-05T05:56:52.470618Z3
        encr_public_key: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
        updated: 2026-04-05T05:56:52.470618Z7
    vlookup_search_parameters:
      type: object
      properties:
        country:
          type: string
          description: Country code
          format: string
          example: IND
        domain:
          type: string
          description: Industry domain of the subscriber.
          format: string
          example: nic2004:52110
        type:
          type: string
          description: buyerApp or sellerApp.
          format: string
          example: sellerApp or byerApp
        city:
          type: string
          description: City code.
          format: string
          example: std:080
        subscriber_id:
          type: string
          description: subscriber id.
          format: string
          example: sit.grab.in/ondc
    vlookup_body:
      required:
      - country
      - domain
      - request_id
      - search_parameters
      - sender_subscriber_id
      - signature
      - timestamp
      type: object
      properties:
        sender_subscriber_id:
          type: string
          description: A unique ID describing a subscriber on a network.
        request_id:
          type: string
          description: Country code as per ISO 3166-1 and ISO 3166-2 format
        timestamp:
          type: string
          description: request timestamp to avoid replay attack
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        search_parameters:
          $ref: '#/components/schemas/vlookup_search_parameters'
        signature:
          type: string
          description: signature
          format: string
          example: Y8Q8yyVI4zCrsCX3e1WlKfJL8Vd7GRBjUoITIH1ISVmDfwxRfJ3xgLu0Pfw4seKRTaGuOdyxDFdVspJckdPFAA==
    vlookup_key_pair:
      type: object
      properties:
        signing_public_key:
          type: string
          description: Signing Public Key
          example: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
        encr_public_key:
          type: string
          description: Encryption Public Key
          example: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
        valid_from:
          type: string
          description: Keys valid from
          format: string ($date-time)
          example: 2022-04-05T05:56:52.470618Z3
        valid_until:
          type: string
          description: Keys valid until
          format: string ($date-time)
          example: 2026-04-05T05:56:52.470618Z7
      example:
        signing_public_key: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
        valid_until: 2026-04-05T05:56:52.470618Z7
        valid_from: 2022-04-05T05:56:52.470618Z3
        encr_public_key: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
    vlookup_seller_on_record:
      type: object
      properties:
        unique_key_id:
          type: string
          description: UUID
          format: string (UUID)
          example: 22a8a67a-76d9-459b-867c-085dda2939ec
        city_code:
          type: string
          description: City code
          format: string
          example: std:080
        key_pair:
          $ref: '#/components/schemas/vlookup_key_pair'
      example:
        unique_key_id: 22a8a67a-76d9-459b-867c-085dda2939ec
        key_pair:
          signing_public_key: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
          valid_until: 2026-04-05T05:56:52.470618Z7
          valid_from: 2022-04-05T05:56:52.470618Z3
          encr_public_key: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
        city_code: std:080
    vlookup_network_participant:
      type: object
      properties:
        subscriber_url:
          type: string
          description: URL to be verified and configured for network participation.The
            given URL should have valid SSL Certificate that should be able to pass
            OCSP check. https://certificatetools.com/ocsp-checker can be used to check
            prior to submitting the request.
          format: string
          example: /test4
        domain:
          type: string
          description: Industry domain of the subscriber.
          format: string
          example: nic2004:52110
        type:
          type: string
          description: buyerApp or sellerApp
          format: string
          example: sellerApp
        msn:
          type: boolean
          description: true or false
          example: true
        city_code:
          type: string
          description: City code
          format: string
          example: std:080
        seller_on_record:
          type: array
          items:
            $ref: '#/components/schemas/vlookup_seller_on_record'
      example:
        seller_on_record:
        - unique_key_id: 22a8a67a-76d9-459b-867c-085dda2939ec
          key_pair:
            signing_public_key: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
            valid_until: 2026-04-05T05:56:52.470618Z7
            valid_from: 2022-04-05T05:56:52.470618Z3
            encr_public_key: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
          city_code: std:080
        - unique_key_id: 22a8a67a-76d9-459b-867c-085dda2939ec
          key_pair:
            signing_public_key: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
            valid_until: 2026-04-05T05:56:52.470618Z7
            valid_from: 2022-04-05T05:56:52.470618Z3
            encr_public_key: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
          city_code: std:080
        subscriber_url: /test4
        domain: nic2004:52110
        msn: true
        city_code: std:080
        type: sellerApp
    inline_response_200_3:
      type: object
      properties:
        subscriber_id:
          type: string
          description: A unique ID describing a subscriber on a network.
          format: string
          example: pilot-gateway-1.beckn.nsdl.co.in/option1
        country:
          type: string
          description: Country code
          format: string
          example: IND
        city:
          type: string
          description: City code
          format: string
          example: std:080
        signing_public_key:
          type: string
          description: Signing Public Key
          example: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
        encr_public_key:
          type: string
          description: Encryption Public Key
          example: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
        valid_from:
          type: string
          description: Keys valid from
          format: string ($date-time)
          example: 2022-04-05T05:56:52.470618Z3
        valid_until:
          type: string
          description: Keys valid until
          format: string ($date-time)
          example: 2026-04-05T05:56:52.470618Z7
        created:
          type: string
          description: Created timestamp
          format: string ($date-time)
          example: 2026-04-05T05:56:52.470618Z7
        updated:
          type: string
          description: Updated timestamp
          format: string ($date-time)
          example: 2026-04-05T05:56:52.470618Z7
        unique_key_id:
          type: string
          description: Unique key of subcriber
          format: string
          example: dba638cc-20cc-40ea-a08b-b4a39bfb3eab
        network_participant:
          type: array
          items:
            $ref: '#/components/schemas/vlookup_network_participant'
      example:
        country: IND
        signing_public_key: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
        subscriber_id: pilot-gateway-1.beckn.nsdl.co.in/option1
        valid_until: 2026-04-05T05:56:52.470618Z7
        unique_key_id: dba638cc-20cc-40ea-a08b-b4a39bfb3eab
        city: std:080
        created: 2026-04-05T05:56:52.470618Z7
        valid_from: 2022-04-05T05:56:52.470618Z3
        encr_public_key: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
        updated: 2026-04-05T05:56:52.470618Z7
        network_participant:
        - seller_on_record:
          - unique_key_id: 22a8a67a-76d9-459b-867c-085dda2939ec
            key_pair:
              signing_public_key: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
              valid_until: 2026-04-05T05:56:52.470618Z7
              valid_from: 2022-04-05T05:56:52.470618Z3
              encr_public_key: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
            city_code: std:080
          - unique_key_id: 22a8a67a-76d9-459b-867c-085dda2939ec
            key_pair:
              signing_public_key: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
              valid_until: 2026-04-05T05:56:52.470618Z7
              valid_from: 2022-04-05T05:56:52.470618Z3
              encr_public_key: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
            city_code: std:080
          subscriber_url: /test4
          domain: nic2004:52110
          msn: true
          city_code: std:080
          type: sellerApp
        - seller_on_record:
          - unique_key_id: 22a8a67a-76d9-459b-867c-085dda2939ec
            key_pair:
              signing_public_key: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
              valid_until: 2026-04-05T05:56:52.470618Z7
              valid_from: 2022-04-05T05:56:52.470618Z3
              encr_public_key: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
            city_code: std:080
          - unique_key_id: 22a8a67a-76d9-459b-867c-085dda2939ec
            key_pair:
              signing_public_key: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
              valid_until: 2026-04-05T05:56:52.470618Z7
              valid_from: 2022-04-05T05:56:52.470618Z3
              encr_public_key: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
            city_code: std:080
          subscriber_url: /test4
          domain: nic2004:52110
          msn: true
          city_code: std:080
          type: sellerApp
    Entity_gst:
      type: object
      properties:
        legal_entity_name:
          type: string
          example: ABC Incorporates
        business_address:
          type: string
          example: "Trade World, Mansarpur, Coorg, Karnataka 333333"
        city_code:
          type: array
          items:
            $ref: '#/components/schemas/City'
        gst_no:
          type: string
          example: 07AAACN2082N4Z7
    Entity_pan:
      type: object
      properties:
        name_as_per_pan:
          type: string
          description: This shall be used to match the name as per PAN with Income
            Tax Department
          example: ABC Incorporates
        pan_no:
          type: string
          description: Permanent Account Number issued by Income Tax Department. First
            five alphabets followed by four numeric followed by one alphabet
          example: ASDFP7657Q
        date_of_incorporation:
          type: string
          description: DD/MM/YYYY format
          format: date
    inline_response_200_message:
      required:
      - ack
      type: object
      properties:
        ack:
          $ref: '#/components/schemas/Ack'
      example:
        ack:
          status: ACK
